version: "3.8"

services:
  postgres_db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lesiaukr
      POSTGRES_DB: hw02
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    restart: always

  fastapi_app:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:lesiaukr@postgres_db:5432/hw02
    volumes:
      - .:/app
    networks:
      - app_network
    restart: always # Автоматичний перезапуск застосунку при збої

networks:
  app_network:

volumes:
  postgres_data:
